[package]
name = "distributed_channel"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5.13"
libp2p = { version = "0.52", features = ["tcp", "cbor", "quic", "tls", "dns", "noise", "yamux", "websocket", "ping", "macros", "gossipsub", "mdns", "tokio", "request-response", "json", "identify", "floodsub"] }
serde = { version = "1.0.210", features = ["serde_derive"] }
futures = "0.3.21"
tokio = { version = "1.40.0", features = ["io-std", "macros", "rt-multi-thread"] }
